[teleport_hosts]
# Teleport-protected hosts must use the full Teleport hostname format:
# {node-name}.{teleport-cluster-domain}
rhel01-nostromo.demoredhat.com.sean-test.teleport.sh ansible_user=ec2-user
ansible-1.example.com.sean-test.teleport.sh ansible_user=ec2-user
